### PR TITLE
#487 : Fix build master script so it works with vanilla uPortal with uPortal context

### LINKED ISSUE #487: fix build master script
We need to update build master to incorporate the new `override.js` workflow.

### PR DESCRIPTION
**Pull request by timlevett**
+ Remove `master-app-config.js`
+ Add in `master-override.js`
+ Fix `build.sh` to work with `override.js`

Resolves #487

### CODE REVIEW

File: angularjs-portal-home/src/main/webapp/js/master-override.js [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+            'base'        : '/uPortal/api/',
+            'layout'      : 'layoutDoc?tab=UW Bucky Home',
+            'layoutTab' : 'UW Bucky Home',
+            'marketplace' : {
+                'base' : 'marketplace/',
+                'entry' : 'entry/',
+                'entries' : 'entries.json'
+            },
+            'notificationsURL' : '/web/staticFeeds/notifications.json',
+            'groupURL' : '/uPortal/api/groups'
```
Comment (bjagg) [inline angularjs-portal-home/src/main/webapp/js/master-override.js]: Need a comma

Comment (timlevett) [inline angularjs-portal-home/src/main/webapp/js/master-override.js]: Nice catch!

**Comment by vertein** [comment]
:+1:
